// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package inject

import (
	"github.com/KScaesar/IsCoolLab2024/pkg/adapters"
	"github.com/KScaesar/IsCoolLab2024/pkg/adapters/cli"
	"github.com/KScaesar/IsCoolLab2024/pkg/adapters/database"
	"github.com/KScaesar/IsCoolLab2024/pkg/app"
)

// Injectors from wire.go:

func NewInfra(conf *database.GormConfing) (*adapters.Infra, error) {
	db, err := database.NewGrom(conf)
	if err != nil {
		return nil, err
	}
	infra := &adapters.Infra{
		Database: db,
	}
	return infra, nil
}

func NewAppService(infra *adapters.Infra) *app.Service {
	db := infra.Database
	userRepository := database.NewUserRepository(db)
	fileSystemRepository := database.NewFileSystemRepository(db)
	userUseCase := app.NewUserUseCase(userRepository, fileSystemRepository)
	folderUseCase := app.NewFolderUseCase(fileSystemRepository)
	service := &app.Service{
		UserService:   userUseCase,
		FolderService: folderUseCase,
	}
	return service
}

func NewRootCommand(infra *adapters.Infra) *cli.Command {
	service := NewAppService(infra)
	command := cli.NewRootCommand(service)
	return command
}
